Add tests
everycache-group/everycache-app pull request #13
Opened 2021-10-03 19:00 UTC by Nieminik

2021-12-22 13:52 UTC, Nieminik commented
@Yamsha75 We basically have full coverage as of now. Please review the changes

2022-02-28 00:23 UTC, Nieminik commented
Fixed the tests.
97% coverage as of now.
@Yamsha75 Let's get this one over with.

2022-02-28 17:17 UTC, Yamsha75 requested changes
Apart from a few empty lines at the beginning of certain files the only issue I found was not updating Pipfile.lock. Please do that and we'll be ready for merge

2022-02-28 17:17 UTC, Yamsha75 commented on api/everycache_api/tests/factories/cache_comment_factory.py
> +
Please remove this emty line

2022-02-28 17:17 UTC, Yamsha75 commented on api/everycache_api/tests/factories/cache_visit_factory.py
> +
Please remove this empty line

2022-02-28 17:17 UTC, Yamsha75 commented on api/everycache_api/tests/helpers.py
> +
Please remove this empty line

2022-02-28 20:26 UTC, Yamsha75 approved these changes

2022-02-28 20:27 UTC, merged